import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css';
import TanstackProvider from '@/providers/TanstackProvider'
import { ToastContainer } from 'react-toastify';
import ReduxProvider from '@/providers/redux/provider';
import Spinner from '@/components/spinner/spinner';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <TanstackProvider>
          <ReduxProvider>
            <Spinner />
            <ToastContainer />
            {children}
          </ReduxProvider>
        </TanstackProvider>
      </body>
    </html>
  )
}
